### ISSUE TITLE
NotImplementedError: TODO: Add support for Opcode BININT

### ISSUE THREAD

**Issue by abenavidesmeli** [trailofbits/fickling#12]
File "/Users/abenavides/workspace/enricher/fury_fda-models-hub-enricher/venvpython3/lib/python3.8/site-packages/fickling/pickle.py", line 106, in __new__
    raise NotImplementedError(f"TODO: Add support for Opcode {info.name}")
NotImplementedError: TODO: Add support for Opcode BININT

**Comment by suhacker1** [comment]
Hey! Would it be possible for you to provide a code snippet that results in this error?

**Comment by ESultanik** [comment]
This is now resolved in Fickling v0.0.3, which is now available on PyPI.
