### ISSUE TITLE
multiple pickles can be stacked in one file

### ISSUE THREAD

**Issue by coldwaterq** [trailofbits/fickling#20]
since pickles aren't a file type you can dump multiple into a single file, which some ML frameworks do. As such injections will create a much smaller and incomplete version of the original when using fickling from the cli.

It would be nice to have a flag to determine which pickle to inject into, and to dump the remaining bytes in the file to the output when injection.

When detecting, all pickles in the file should be scanned so that injecting into the seccond pickle doesn't completely bypass all detections.

**Comment by ESultanik** [comment]
Can you give an example of an ML framework that does this? I'd like to have an example file to ensure compatibility.

**Comment by coldwaterq** [comment]
https://catalog.ngc.nvidia.com/orgs/nvidia/models/tacotron2_ljspeech/files is the first public one I found. all the .pt are stacked pickles.

**Comment by McPatate** [comment]
You can also take a look at PyTorch's [legacy save](https://pytorch.org/docs/stable/_modules/torch/serialization.html#save).

IIRC [bert-base-uncased](https://huggingface.co/bert-base-uncased) model weights (`pytorch_model.bin`) are serialized in the old format.

[joblib](https://github.com/joblib/joblib/blob/36c0288ffd4d6e4474c39246745716f881ff5dc9/joblib/numpy_pickle.py) also has an atypical way of pickling its data, not sure if it's multiple pickles in a row though.
