### ISSUE TITLE
torch dependency

### ISSUE THREAD

**Issue by stevemarin** [trailofbits/fickling#92]
Hello and thank you very much for all your hard work! We use `fickling` as a dependency of `polyfile`. Version 0.1.0 added a significant build time for us due to the inclusion of torch as a requirement.

We can continue working with 0.0.8 for now, so we have no complaints. But we were wondering if the torch requirement could be made optional in the future?

Thank you again!

**Comment by suhacker1** [comment]
Thanks for raising this issue! We're looking into this for the next release.
